quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.username=postgres
quarkus.datasource.devservices.password=postgres
quarkus.datasource.devservices.db-name=postgres
quarkus.datasource.devservices.port=55432

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.log.category."org.hibernate.engine.transaction.internal.TransactionImpl".level=DEBUG

quarkus.http.host=0.0.0.0
quarkus.http.port=8080

quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.login-page=/admin/login
quarkus.http.auth.form.error-page=/admin/login?error=true
quarkus.http.auth.form.landing-page=/admin
quarkus.http.auth.form.post-location=/admin/login

quarkus.http.auth.permission.login.paths=/admin/login
quarkus.http.auth.permission.login.policy=permit

quarkus.http.auth.form.logout-page=/admin/logout

quarkus.http.auth.permission.admin.paths=/admin/*
quarkus.http.auth.permission.admin.policy=authenticated

firebase.credentials.path=/home/davtek/TB/observatoire-citoyen-du-climat-firebase-adminsdk-fbsvc-5c05ea96c8.json